---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: post
  labels:
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      name: post
      labels:
        app: post
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: post
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: post
          protocol: TCP
        env:
        - name: POST_DATABASE_HOST
          value:  {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
        - name: ZIPKIN_ENABLED
          value: {{  .Values.zipkinEnabled | default "false" | quote }}
        - name: ZIPKIN_HOST
          value: {{  .Values.zipkinHost | default "zipkin" }}
        - name: ZIPKIN_PORT
          value: {{  .Values.zipkinPort | default "9411" | quote }}
...
