---
apiVersion: v1
kind: Service
metadata:
  name: comment
  labels:
    app: comment
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: comment
